//! MCP servers SSOT + per-agent sync.
//!
//! `mcp_server` is the single source of truth for MCP servers; every agent's
//! config file (`.claude.json`, opencode's `opencode.json`, pi's `mcp.json`)
//! is a projection of the DB, regenerated by [`sync_agent`] whenever a row
//! changes. Each row tracks which agents it is *written into* and whether
//! the native `enabled` flag is on (`enabled_agents`) or off
//! (`disabled_agents` — only formats with a per-server enabled field expose
//! the middle state).
//!
//! Transports are parsed from the agents' native shapes via [`from_native`]
//! (concept keys like `bin`/`arg`/`endpoint` map onto the canonical
//! [`McpTransport`] fields); the canonical id is the slugified name
//! ([`id_for`]), so the same server found in two CLIs merges into one row.

use std::collections::{BTreeMap, HashSet};

use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use serde_json::Value;

use crate::db::{self, home_dir, McpServerRow};
use crate::error::{AppError, AppResult};

pub mod probe;
pub mod providers;

pub use probe::{ProbeResult, probe_transport};

/// Transport kind: stdio subprocess vs http/sse endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum McpKind {
    Stdio,
    Http,
    /// Streamable HTTP (SSE) endpoint.
    Sse,
}

impl McpKind {
    /// Conflict-family: `Sse` and `Http` are the same URL server (one is a
    /// streamable wrapper over the other) — they must never count as a
    /// kind conflict, or the same URL would import as two rows.
    pub fn family(self) -> McpKind {
        match self {
            McpKind::Sse => McpKind::Http,
            other => other,
        }
    }
}

/// Canonical MCP transport shape, independent of any agent's native format.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct McpTransport {
    pub kind: McpKind,
    pub command: Option<String>,
    pub args: Vec<String>,
    pub env: BTreeMap<String, String>,
    pub url: Option<String>,
}

impl Default for McpTransport {
    fn default() -> Self {
        Self {
            kind: McpKind::Stdio,
            command: None,
            args: Vec::new(),
            env: BTreeMap::new(),
            url: None,
        }
    }
}

impl McpTransport {
    /// A transport must be runnable: stdio needs a command, http a url.
    pub fn validate(&self) -> AppResult<()> {
        match self.kind {
            McpKind::Stdio => {
                if self.command.as_deref().map(str::trim).unwrap_or("").is_empty() {
                    return Err(AppError::Validation(
                        "stdio MCP server needs a command".into(),
                    ));
                }
            }
            McpKind::Http | McpKind::Sse => {
                if self.url.as_deref().map(str::trim).unwrap_or("").is_empty() {
                    return Err(AppError::Validation(
                        "http MCP server needs a url".into(),
                    ));
                }
            }
        }
        Ok(())
    }
}

/// Managed MCP server (DB row + in-memory transport). `managed` distinguishes
/// Nestra-owned rows from servers the user configured directly in an agent
/// file (which surface as import candidates instead).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct McpServer {
    pub id: String,
    pub name: String,
    pub transport: McpTransport,
    /// Agents this server is written into with the native enabled flag on.
    pub enabled_agents: Vec<String>,
    /// Agents this server is written into with the native enabled flag off
    /// (`enabled: false`). Only agents whose format carries the field.
    pub disabled_agents: Vec<String>,
    pub managed: bool,
    /// Per-agent env overrides layered on top of `transport.env` at sync
    /// time (the override wins on key clash).
    pub env_overrides: BTreeMap<String, BTreeMap<String, String>>,
}

/// The tri-state per-agent relationship for a server.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AgentMcpState {
    /// Not written into the agent's config.
    Absent,
    /// Written with the native enabled flag off.
    Disabled,
    /// Written with the native enabled flag on.
    Enabled,
}

/// Parse an agent's native MCP entry (concept keys, not field names) into
/// the canonical transport. Claude uses `command`/`args`; pi and opencode
/// may use `bin`/`arg` (command + whitespace-split args), `environment`,
/// and `endpoint`/`url` for http servers.
pub fn from_native(v: &Value) -> AppResult<McpTransport> {
    // Command may be a string () or an array
    // ( — opencode's shape): the first
    // element is the executable, the rest are arguments.
    let (command, cmd_extra_args) = match v.get("bin").or_else(|| v.get("command")) {
        Some(Value::String(s)) => (Some(s.clone()), Vec::new()),
        Some(Value::Array(arr)) => {
            let mut it = arr.iter().filter_map(|x| x.as_str());
            match it.next() {
                Some(c) => (Some(c.to_string()), it.map(String::from).collect()),
                None => (None, Vec::new()),
            }
        }
        _ => (None, Vec::new()),
    };
    let mut args: Vec<String> = v
        .get("arg")
        .and_then(Value::as_str)
        .map(|s| s.split_whitespace().map(String::from).collect())
        .or_else(|| {
            v.get("args").and_then(Value::as_array).map(|arr| {
                arr.iter()
                    .filter_map(|x| x.as_str().map(String::from))
                    .collect()
            })
        })
        .unwrap_or_default();
    args.extend(cmd_extra_args);
    let mut env = BTreeMap::new();
    // Native writers use `environment` (opencode canonical) but some
    // hand-written/legacy entries carry `env` (Claude-style) — read both so
    // env keys (often API keys) survive a dump/import/sync round-trip.
    let env_obj = v
        .get("environment")
        .and_then(Value::as_object)
        .or_else(|| v.get("env").and_then(Value::as_object));
    if let Some(e) = env_obj {
        for (k, val) in e {
            if let Some(s) = val.as_str() {
                env.insert(k.clone(), s.to_string());
            }
        }
    }
    let url = v
        .get("endpoint")
        .or_else(|| v.get("url"))
        .and_then(Value::as_str)
        .map(String::from);
    let kind = match v.get("type").and_then(Value::as_str) {
        Some("sse") => McpKind::Sse,
        Some("http") | Some("remote") => McpKind::Http,
        _ => {
            if url.is_some() {
                McpKind::Http
            } else {
                McpKind::Stdio
            }
        }
    };
    Ok(McpTransport {
        kind,
        command,
        args,
        env,
        url,
    })
}

/// Infallible variant of [`from_native`] for scan paths — an unparseable
/// entry degrades to an empty stdio transport rather than failing the scan.
pub fn dump(v: &Value) -> McpTransport {
    from_native(v).unwrap_or_default()
}

/// The native `enabled` flag, when the format carries one.
fn native_enabled(v: &Value) -> Option<bool> {
    v.get("enabled").and_then(Value::as_bool)
}

/// Canonical server id from its name: lowercase, non-alphanumerics collapse
/// to single dashes, trailing dashes trimmed. `"Foo Bar-"` → `"foo-bar"`.
pub fn id_for(name: &str) -> String {
    slugify(name)
}

/// Slugify a string into a canonical id.
pub fn slugify(s: &str) -> String {
    let mut out = String::new();
    let mut prev_dash = false;
    for c in s.trim().to_lowercase().chars() {
        if c.is_alphanumeric() {
            out.push(c);
            prev_dash = false;
        } else if !prev_dash && !out.is_empty() {
            out.push('-');
            prev_dash = true;
        }
    }
    out.trim_end_matches('-').to_string()
}

/// Rehydrate a managed server from its DB row. `transport_json` carries the
/// canonical [`McpTransport`]; per-agent env overrides live in the
/// `mcp_server_env` table.
pub fn row_to_server(conn: &Connection, row: McpServerRow) -> AppResult<McpServer> {
    let parsed: Value = serde_json::from_str(&row.transport_json).unwrap_or(Value::Null);
    let transport = serde_json::from_value(parsed).unwrap_or_default();
    let env_overrides = db::list_mcp_env_overrides(conn, &row.id)?;
    // Registry churn guard: agent ids that no MCP provider knows (renamed or
    // removed registry entries, e.g. the `claude-code` → `claude-code-cli`
    // rename) must never surface as toggles or be re-synced. Filtered at the
    // read boundary; `sync_all` persists the pruned set so the DB heals.
    let known = |a: &str| providers::agent_exists(a);
    Ok(McpServer {
        id: row.id,
        name: row.name,
        transport,
        enabled_agents: row
            .enabled_agents
            .into_iter()
            .filter(|a| known(a))
            .collect(),
        disabled_agents: row
            .disabled_agents
            .into_iter()
            .filter(|a| known(a))
            .collect(),
        managed: true,
        env_overrides,
    })
}

/// All managed servers, in DB order.
pub fn list(conn: &Connection) -> AppResult<Vec<McpServer>> {
    db::list_mcp_servers(conn)?
        .into_iter()
        .map(|r| row_to_server(conn, r))
        .collect()
}

/// Persist a server's DB row (transport + agent sets). The caller syncs the
/// affected agents' files afterwards. `env_overrides` rides along inside
/// `transport_json` so a reload round-trips them.
fn upsert(conn: &Connection, server: &McpServer) -> AppResult<()> {
    let tj = serde_json::to_string(&server.transport)?;
    db::upsert_mcp_server(
        conn,
        &server.id,
        &server.name,
        &tj,
        &server.enabled_agents,
        &server.disabled_agents,
    )?;
    db::replace_mcp_env_overrides(conn, &server.id, &server.env_overrides)
}

/// Save (create or update) a managed server with the canonical id derived
/// from its name. A rename (canonical id shift) drops the old row and its
/// CLI entries. Returns the saved server with the canonical id applied.
pub fn save(conn: &Connection, server: &McpServer) -> AppResult<McpServer> {
    server.transport.validate()?;
    let canonical = id_for(&server.name);
    let new_id = if server.id == canonical {
        server.id.clone()
    } else {
        canonical
    };
    // Rename cleanup: the canonical id shifted — drop the old row and its
    // per-agent file entries before writing the new one.
    if new_id != server.id && !server.id.is_empty() {
        // Renaming onto an EXISTING row's id must fail loudly: the upsert
        // below uses ON CONFLICT(id) DO UPDATE, which would otherwise
        // silently overwrite the other server's row (and its CLI entries).
        if let Some(other) = db::get_mcp_server(conn, &new_id)? {
            return Err(AppError::Validation(format!(
                "renaming to '{}' collides with existing server '{}'",
                new_id, other.name
            )));
        }
        if let Some(old) = db::get_mcp_server(conn, &server.id)? {
            let old_server = row_to_server(conn, old)?;
            for agent in old_server
                .enabled_agents
                .iter()
                .chain(old_server.disabled_agents.iter())
            {
                providers::remove_server(agent, &old_server.name)?;
            }
            // Old row + its env overrides disappear atomically.
            let tx = conn.unchecked_transaction()?;
            db::delete_mcp_server(&tx, &server.id)?;
            tx.commit()?;
        }
    }
    persist(conn, server, new_id)
}

/// Persist a server under an EXPLICIT id (used by import to pin a
/// kind-conflict suffix like `dual-pi`). The caller's id is trusted as-is —
/// no name canonicalization, no rename cleanup.
pub fn save_with_id(
    conn: &Connection,
    server: &McpServer,
    _forced_id: Option<&str>,
) -> AppResult<McpServer> {
    server.transport.validate()?;
    persist(conn, server, server.id.clone())
}

/// Shared write path: upsert + re-project the DB into every agent the server
/// is written on — INCLUDING agents it used to be written on: an agent
/// removed from the sets still needs its provider file regenerated so the
/// entry is dropped from disk (not just from the DB).
fn persist(conn: &Connection, server: &McpServer, id: String) -> AppResult<McpServer> {
    let mut saved = server.clone();
    saved.id = id;
    // Snapshot the OLD written set (pre-upsert) so removed agents get synced.
    let old_written: Vec<String> = db::get_mcp_server(conn, &saved.id)?
        .map(|r| {
            r.enabled_agents
                .iter()
                .chain(r.disabled_agents.iter())
                .cloned()
                .collect()
        })
        .unwrap_or_default();
    upsert(conn, &saved)?;
    let mut agents: HashSet<String> = saved
        .enabled_agents
        .iter()
        .chain(saved.disabled_agents.iter())
        .cloned()
        .collect();
    for a in old_written {
        agents.insert(a);
    }
    for a in agents {
        sync_agent(conn, &a)?;
    }
    Ok(saved)
}
/// Add/remove one agent from a server's enabled set, then sync (test
/// helper — the live path is ).  means *absent*
/// — the entry is dropped from the agent's file, not merely turned off (see
///  for the "written but disabled" state).
#[cfg(test)]
pub fn toggle(
    conn: &Connection,
    id: &str,
    agent: &str,
    enabled: bool,
) -> AppResult<McpServer> {
    if !providers::agent_exists(agent) {
        return Err(AppError::NotFound(format!("unknown agent: {agent}")));
    }
    let mut server = crate::db::get_mcp_server(conn, id)?
        .map(|r| row_to_server(conn, r))
        .ok_or_else(|| AppError::NotFound(format!("mcp server not found: {id}")))??;
    // Track both old and new written sets: an agent being toggled off must still
    // have its provider file regenerated (to drop the server).
    let old_written: Vec<String> = server
        .enabled_agents
        .iter()
        .chain(server.disabled_agents.iter())
        .cloned()
        .collect();
    if enabled {
        if !server.enabled_agents.iter().any(|c| c == agent) {
            server.enabled_agents.push(agent.to_string());
        }
        server.disabled_agents.retain(|c| c != agent);
    } else {
        server.enabled_agents.retain(|c| c != agent);
        server.disabled_agents.retain(|c| c != agent);
    }
    let new_written: Vec<String> = server
        .enabled_agents
        .iter()
        .chain(server.disabled_agents.iter())
        .cloned()
        .collect();
    upsert(conn, &server)?;
    for a in old_written
        .into_iter()
        .chain(new_written)
        .collect::<std::collections::HashSet<_>>()
    {
        sync_agent(conn, &a)?;
    }
    Ok(server)
}

/// Set one agent's per-server state, then sync. `Enabled` writes with the
/// native flag on, `Disabled` keeps the entry written with it off (formats
/// that carry one), `Absent` drops the entry from the file entirely. Moving
/// an agent between states clears it from the other list — the two are kept
/// disjoint.
pub fn set_state(
    conn: &Connection,
    id: &str,
    agent: &str,
    state: AgentMcpState,
) -> AppResult<McpServer> {
    if !providers::agent_exists(agent) {
        return Err(AppError::NotFound(format!("unknown agent: {agent}")));
    }
    let mut server = crate::db::get_mcp_server(conn, id)?
        .map(|r| row_to_server(conn, r))
        .ok_or_else(|| AppError::NotFound(format!("mcp server not found: {id}")))??;
    let old_written: Vec<String> = server
        .enabled_agents
        .iter()
        .chain(server.disabled_agents.iter())
        .cloned()
        .collect();
    match state {
        AgentMcpState::Absent => {
            server.enabled_agents.retain(|c| c != agent);
            server.disabled_agents.retain(|c| c != agent);
        }
        AgentMcpState::Disabled => {
            // Only formats with a per-server `enabled` field can express
            // "written but disabled". For everyone else (claude-code-cli, pi-cli) the
            // flag would be silently DROPPED by to_native — the DB would say
            // disabled while the agent loads the server enabled. Degrade to
            // absent instead: the entry leaves the agent's file entirely.
            let supports = providers::for_agent(agent)
                .map(|p| p.supports_enabled())
                .unwrap_or(false);
            if supports {
                server.enabled_agents.retain(|c| c != agent);
                if !server.disabled_agents.iter().any(|c| c == agent) {
                    server.disabled_agents.push(agent.to_string());
                }
            } else {
                server.enabled_agents.retain(|c| c != agent);
                server.disabled_agents.retain(|c| c != agent);
            }
        }
        AgentMcpState::Enabled => {
            server.disabled_agents.retain(|c| c != agent);
            if !server.enabled_agents.iter().any(|c| c == agent) {
                server.enabled_agents.push(agent.to_string());
            }
        }
    }
    let new_written: Vec<String> = server
        .enabled_agents
        .iter()
        .chain(server.disabled_agents.iter())
        .cloned()
        .collect();
    upsert(conn, &server)?;
    for a in old_written
        .into_iter()
        .chain(new_written)
        .collect::<std::collections::HashSet<_>>()
    {
        sync_agent(conn, &a)?;
    }
    Ok(server)
}

/// Regenerate an agent's provider file to match the DB: for every DB server
/// written on `agent` (enabled **or** disabled), write its canonical
/// transport — with the native enabled flag on/off respectively; for every DB
/// server NOT written on `agent`, remove it from that agent's file if present.
/// Servers not known to the DB are left untouched (never clobber hand-edited
/// config).
pub fn sync_agent(conn: &Connection, agent: &str) -> AppResult<()> {
    let Some(p) = providers::for_agent(agent) else {
        return Err(AppError::NotFound(format!("unknown agent: {agent}")));
    };
    let path = p.config_path(&home_dir()?);
    if !path.exists() {
        // Missing config file: create it (empty JSON object) and fall through
        // to the normal apply path. Toggle callers already verified the agent
        // is registered; sync_all iterates registered providers only. A
        // no-op-write would otherwise leave toggles pretending to succeed
        // while writing nothing. `apply_at_path`/`opencode_apply` treat an
        // empty file as an empty object root.
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, "{}")?;
    }
    let raw = std::fs::read_to_string(&path)?;
    let (enabled, disabled, remove): (Vec<McpServer>, Vec<McpServer>, Vec<String>) = {
        let all = list(conn)?;
        let mut en = Vec::new();
        let mut dis = Vec::new();
        let mut rem = Vec::new();
        for s in all {
            if s.enabled_agents.iter().any(|a| a == agent) {
                en.push(s);
            } else if s.disabled_agents.iter().any(|a| a == agent) {
                dis.push(s);
            } else {
                rem.push(s.name.clone());
            }
        }
        (en, dis, rem)
    };
    // Write enabled ones with the flag on and disabled ones with it off;
    // drop the rest. A file that isn't valid JSON refuses the rewrite
    // (apply errors) instead of being replaced by an empty object.
    let native_map = p.to_native_map(&enabled, &disabled);
    let out = p.apply(&raw, &native_map, &remove)?;
    atomic_write_cfg(&path, &out)
}

/// Persist a CLI's provider file atomically.
fn atomic_write_cfg(path: &std::path::Path, data: &str) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    crate::config_writer::atomic_write(path, data.as_bytes())
}

// ---- Import ----

/// An MCP server present in an agent file that isn't a managed Nestra row
/// yet, **aggregated across agents**: the same server (by `id_for(name)`)
/// installed in several agents shows up as a single candidate with multiple
/// `agent_ids`, so the user sees one thing to import rather than N.
#[derive(Debug, Clone, Serialize)]
pub struct ImportCandidate {
    pub name: String,
    /// Canonical id (`id_for(name)`). The UI passes this back on import.
    pub id: String,
    /// Serialized `McpTransport` of the first occurrence (display only).
    pub transport_json: String,
    /// Agents this candidate was found in and is not yet managed for.
    pub agent_ids: Vec<String>,
    /// Agents where the entry was found with the native enabled flag off
    /// (`enabled: false`). Importing preserves that state — the agent lands
    /// in `disabled_agents`, not `enabled_agents`.
    #[serde(default)]
    pub disabled_in: Vec<String>,
    /// True if the transport *kind* differs across the agents in `agent_ids`
    /// (e.g. stdio in one, http in another) — surfaces a mixed-transport
    /// warning in the UI.
    pub transports_conflict: bool,
    /// `(agent_id, config path)` for each source, for display.
    pub native_paths: Vec<(String, String)>,
}

/// Discover MCP servers in CLI provider files that aren't yet managed,
/// aggregated by canonical id so a server installed in several CLIs is one
/// candidate.
pub fn import_scan(conn: &Connection) -> AppResult<Vec<ImportCandidate>> {
    let managed: std::collections::HashMap<String, HashSet<String>> = list(conn)?
        .into_iter()
        .map(|s| {
            let agents = s
                .enabled_agents
                .iter()
                .chain(s.disabled_agents.iter())
                .cloned()
                .collect();
            (s.id, agents)
        })
        .collect();
    import_scan_unmanaged(&managed)
}

/// File-scan half of `import_scan`. Takes the set of already-managed ids
/// (each mapped to the agents it is managed under), no `&Connection` —
/// callers hold no DB lock during provider-file reads.
pub fn import_scan_unmanaged(
    managed: &std::collections::HashMap<String, HashSet<String>>,
) -> AppResult<Vec<ImportCandidate>> {
    let home = home_dir()?;

    // Group raw occurrences by canonical id.
    #[derive(Default)]
    struct Acc {
        name: Option<String>,
        transport: Option<McpTransport>,
        kinds: HashSet<String>,
        agent_ids: Vec<String>,
        disabled_in: Vec<String>,
        native_paths: Vec<(String, String)>,
    }
    let mut by_id: std::collections::BTreeMap<String, Acc> = std::collections::BTreeMap::new();

    for p in providers::all() {
        let path = p.config_path(&home);
        if !path.exists() {
            continue;
        }
        let Ok(raw) = std::fs::read_to_string(&path) else { continue };
        for (name, native) in p.read_raw(&raw) {
            let id = id_for(&name);
            // Skip when this id is ALREADY MANAGED for THIS CLI. An id
            // managed only under other CLIs is still importable here —
            // skipping it outright would make partially-managed servers
            // permanently unimportable (e.g. a pi server that never got
            // synced to opencode).
            let a = p.agent_id();
            if managed
                .get(&id)
                .map(|agents| agents.contains(a))
                .unwrap_or(false)
            {
                continue;
            }
            let kind = dump(&native).kind;
            // Family-level kind (Sse folds into Http): only a real
            // stdio-vs-http conflict should surface as `transports_conflict`.
            let kind_key = format!("{:?}", kind.family());
            let acc = by_id.entry(id.clone()).or_default();
            if acc.name.is_none() {
                acc.name = Some(name.clone());
                acc.transport = Some(dump(&native));
            }
            acc.kinds.insert(kind_key);
            if !acc.agent_ids.iter().any(|c| c == a) {
                acc.agent_ids.push(a.to_string());
            }
            if native_enabled(&native) == Some(false) && !acc.disabled_in.iter().any(|c| c == a) {
                acc.disabled_in.push(a.to_string());
            }
            acc.native_paths
                .push((p.agent_id().to_string(), path.to_string_lossy().to_string()));
        }
    }

    let mut out = Vec::new();
    for (id, acc) in by_id {
        let name = acc.name.unwrap_or_else(|| id.clone());
        let transport = acc.transport.unwrap_or(McpTransport {
            kind: McpKind::Stdio,
            command: None,
            args: vec![],
            env: BTreeMap::new(),
            url: None,
        });
        let tj = serde_json::to_string(&transport)?;
        out.push(ImportCandidate {
            name,
            id,
            transport_json: tj,
            agent_ids: acc.agent_ids,
            disabled_in: acc.disabled_in,
            transports_conflict: acc.kinds.len() > 1,
            native_paths: acc.native_paths,
        });
    }
    // Stable order: by name then id.
    out.sort_by(|a, b| a.name.cmp(&b.name).then(a.id.cmp(&b.id)));
    Ok(out)
}

/// Import every unmanaged candidate, enabling it on all the CLIs it was found
/// in. Returns the resulting managed servers. Best-effort: per-CLI failures are
/// collected but don't abort the batch.
pub fn import_all(conn: &Connection) -> AppResult<Vec<McpServer>> {
    let candidates = import_scan(conn)?;
    let mut errors: Vec<String> = Vec::new();
    for cand in &candidates {
        for an_id in &cand.agent_ids {
            if let Err(e) = import_one(conn, an_id, &cand.name) {
                errors.push(format!("{}: {e}", cand.name));
            }
        }
    }
    if !errors.is_empty() {
        return Err(AppError::Internal(format!(
            "some imports failed: {}",
            errors.join("; ")
        )));
    }
    // Read the authoritative post-import state from the DB rather than the
    // per-call return values: import_one returns the row as of *that* call, so
    // a cross-CLI merge would otherwise show stale enabled_agents.
    list(conn)
}

/// Import a single unmanaged server (found via `import_scan`) and add it to
/// the DB as managed, enabled on the CLI it came from. Semantic merge: if a
/// canonical row already exists with the same name+transport, we just add the
/// CLI to its enabled set (toggling it on), never overwrite it.
pub fn import_one(conn: &Connection, agent_id: &str, name: &str) -> AppResult<McpServer> {
    let home = home_dir()?;
    let Some(p) = providers::for_agent(agent_id) else {
        return Err(AppError::Validation(format!("unknown agent: {agent_id}")));
    };
    let path = p.config_path(&home);
    if !path.exists() {
        return Err(AppError::NotFound(format!("no {agent_id} config at {}", path.display())));
    }
    let raw = std::fs::read_to_string(&path)?;
    let mut found: Option<(String, serde_json::Value)> = None;
    for (n, v) in p.read_raw(&raw) {
        // Match by exact name OR by canonical id: the scan aggregates by
        // `id_for(name)`, so a case/whitespace variant of the same name
        // ("My Server" vs "my-server") must resolve to the same entry.
        if n == name || id_for(&n) == id_for(name) {
            found = Some((n, v));
            break;
        }
    }
    let (fname, native) = found
        .ok_or_else(|| AppError::NotFound(format!("{name} not found in {}", path.display())))?;
    let transport = dump(&native);
    transport.validate()?;
    // File entry carries the native enabled flag off — preserve it by landing
    // the agent in `disabled_agents` rather than force-enabling on import.
    let found_disabled = native_enabled(&native) == Some(false);

    let id = id_for(&fname);
    if let Some(existing) = crate::db::get_mcp_server(conn, &id)? {
        // Semantic merge: treat same name + same transport *kind* (both stdio,
        // or both http/sse) as the same server even if a provider added an
        // extra field or ordered args differently. Only a kind mismatch (stdio
        // vs http) is treated as genuinely different servers.
        let ex = row_to_server(conn, existing)?;
        // Same transport FAMILY (stdio vs http/sse are the only real
        // conflicts; Sse and Http are the same URL server) → merge.
        if ex.transport.kind.family() == transport.kind.family() {
            let mut merged = ex;
            if found_disabled {
                merged.enabled_agents.retain(|c| c != agent_id);
                if !merged.disabled_agents.iter().any(|c| c == agent_id) {
                    merged.disabled_agents.push(agent_id.to_string());
                }
            } else {
                merged.disabled_agents.retain(|c| c != agent_id);
                if !merged.enabled_agents.iter().any(|c| c == agent_id) {
                    merged.enabled_agents.push(agent_id.to_string());
                }
            }
            save(conn, &merged)
        } else {
            // Same name, incompatible transport kind on another agent — keep
            // both (do not clobber). Place this one at a distinct, suffixed id
            // via `save_with_id` so it isn't folded back onto the canonical id.
            let suffix = slugify(agent_id);
            let alt_id = format!("{id}-{suffix}");
            let server = McpServer {
                id: alt_id,
                name: fname,
                transport,
                enabled_agents: if found_disabled {
                    Vec::new()
                } else {
                    vec![agent_id.to_string()]
                },
                disabled_agents: if found_disabled {
                    vec![agent_id.to_string()]
                } else {
                    Vec::new()
                },
                managed: true,
                env_overrides: BTreeMap::new(),
            };
            save_with_id(conn, &server, None)
        }
    } else {
        let server = McpServer {
            id,
            name: fname,
            transport,
            enabled_agents: if found_disabled {
                Vec::new()
            } else {
                vec![agent_id.to_string()]
            },
            disabled_agents: if found_disabled {
                vec![agent_id.to_string()]
            } else {
                Vec::new()
            },
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(conn, &server)
    }
}

/// Re-project the DB into every known agent's config file. For each row +
/// agent pair, write the entry if the row is written on that agent (enabled
/// or disabled), remove it otherwise. Useful when the user hand-edits an
/// agent config out from under Nestra and wants it re-aligned with the DB.
pub fn sync_all(conn: &Connection) -> AppResult<()> {
    let rows = crate::db::list_mcp_servers(conn)?;
    // TODO: consolidate into a per-platform `sync_enabled_to` for an O(M) pass
    // instead of the current O(rows × agents).
    for p in providers::all() {
        let agent = p.agent_id();
        for row in &rows {
            if row.enabled_agents.iter().any(|c| c == agent)
                || row.disabled_agents.iter().any(|c| c == agent)
            {
                sync_agent(conn, agent)?;
            } else {
                providers::remove_server(agent, &row.name)?;
            }
        }
    }
    // Registry-churn repair: persist the pruned agent lists so legacy ids
    // (renamed/removed registry entries) stop accumulating. The read boundary
    // already filters them (`row_to_server`); this makes the cleanup durable.
    for row in &rows {
        let known = |a: &str| providers::agent_exists(a);
        let kept_enabled: Vec<String> = row
            .enabled_agents
            .iter()
            .filter(|a| known(a))
            .cloned()
            .collect();
        let kept_disabled: Vec<String> = row
            .disabled_agents
            .iter()
            .filter(|a| known(a))
            .cloned()
            .collect();
        if kept_enabled != row.enabled_agents || kept_disabled != row.disabled_agents {
            db::update_mcp_server_agents(conn, &row.id, &kept_enabled, &kept_disabled)?;
        }
    }
    Ok(())
}

/// Delete a managed server (from DB and all agents it was written on).
pub fn delete(conn: &Connection, id: &str) -> AppResult<()> {
    let r = crate::db::get_mcp_server(conn, id)?;
    let Some(r) = r else { return Ok(()) };
    let server = row_to_server(conn, r)?;
    crate::db::delete_mcp_server(conn, id)?;
    // Explicit per-agent removal. The old `sync_agent`-based loop left the
    // entry behind because once the DB row is gone the name has no remaining
    // enabled match, so the rebuild step neither writes nor names it for
    // removal.
    for agent in server
        .enabled_agents
        .iter()
        .chain(server.disabled_agents.iter())
    {
        providers::remove_server(agent, &server.name)?;
    }
    Ok(())
}

/// Stop managing a server: drop its DB row (and env overrides) but LEAVE the
/// entries already written into agent config files in place. The server keeps
/// working in those agents and re-surfaces as an Importable candidate — the
/// inverse of [`import_one`]. Contrast [`delete`], which also strips the
/// entries from every agent config. Idempotent: a missing id is a no-op
/// (matching `delete`). The MCP page's "restore" button maps here.
pub fn unmanage(conn: &Connection, id: &str) -> AppResult<()> {
    // `db::delete_mcp_server` also cleans up `mcp_server_env`, so no orphaned
    // override rows. We deliberately do NOT call `providers::remove_server` —
    // keeping the config entries is what makes this "unmanage" rather than
    // "delete", and once the DB row is gone `sync_agent` won't touch a
    // name with no matching row (same rule that preserves hand-authored
    // entries), so the leftover entries are stable.
    crate::db::delete_mcp_server(conn, id)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn temp_home() -> (PathBuf, tempfile::TempDir) {
        let dir = tempfile::Builder::new()
            .prefix("nestra-mcp-test-")
            .tempdir()
            .expect("tempdir");
        (dir.path().to_path_buf(), dir)
    }

    #[test]
    fn semantic_parses_command_variants() {
        // Concept keys, not field names: "bin" is a command key, "arg" a args key.
        let v = serde_json::json!({
            "bin": "npx",
            "arg": "-y @modelcontextprotocol/server-filesystem /tmp",
            "environment": {"FOO": "bar"}
        });
        let t = from_native(&v).unwrap();
        assert_eq!(t.kind, McpKind::Stdio);
        assert_eq!(t.command.as_deref(), Some("npx"));
        assert!(t.args.contains(&"@modelcontextprotocol/server-filesystem".to_string()));
        assert_eq!(t.env.get("FOO").map(String::as_str), Some("bar"));
    }

    #[test]
    fn semantic_url_detection() {
        let v = serde_json::json!({ "endpoint": "https://example.com/mcp" });
        let t = from_native(&v).unwrap();
        assert_eq!(t.kind, McpKind::Http);
        assert_eq!(t.url.as_deref(), Some("https://example.com/mcp"));
    }

    #[test]
    fn claude_round_trip_sync_preserves_other_keys() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);
        let config = home.join(".claude.json");
        std::fs::create_dir_all(config.parent().unwrap()).unwrap();
        std::fs::write(&config, r#"{"mcpServers":{},"theme":"dark"}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "filesystem".into(),
            name: "filesystem".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["-y".into(), "@mcps/filesystem".into()],
                env: Default::default(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();

        let written = std::fs::read_to_string(&config).unwrap();
        assert!(written.contains("\"theme\": \"dark\""), "must preserve unrelated key");
        assert!(written.contains("\"filesystem\""), "must add server");

        // toggle off removes from the file
        toggle(&conn, "filesystem", "claude-code-cli", false).unwrap();
        let written = std::fs::read_to_string(&config).unwrap();
        assert!(!written.contains("\"filesystem\""));
        assert!(written.contains("\"theme\": \"dark\""));
    }

    /// The headline fix: a server installed identically in two CLIs must import
    /// as a *single* managed row enabled on both, not two rows.
    #[test]
    fn cross_cli_dedup_merges_into_one_row() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        // claude: codegraph as stdio
        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(
            &claude,
            r#"{"mcpServers":{"codegraph":{"command":"npx","args":["-y","codegraph"]}}}"#,
        )
        .unwrap();

        // Extra `type` field on one side the other lacks. Before the fix this
        // made transports unequal and they split.
        let pi_dir = home.join(".pi").join("agent");
        std::fs::create_dir_all(&pi_dir).unwrap();
        std::fs::write(
            pi_dir.join("mcp.json"),
            r#"{"mcpServers":{"codegraph":{"type":"stdio","command":"npx","args":["-y","codegraph"]}}}"#,
        )
        .unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let imported = import_all(&conn).unwrap();
        // Exactly one managed row.
        assert_eq!(imported.len(), 1, "should merge into one row, got {imported:?}");
        let s = &imported[0];
        assert_eq!(s.id, "codegraph");
        assert_eq!(s.name, "codegraph");
        assert!(
            s.enabled_agents.iter().any(|c| c == "claude-code-cli"),
            "claude-code should be enabled: {:?}",
            s.enabled_agents
        );
        assert!(
            s.enabled_agents.iter().any(|c| c == "pi-cli"),
            "pi should be enabled: {:?}",
            s.enabled_agents
        );
    }

    /// Different transport *kind* (stdio vs http) under the same name is a
    /// genuine conflict: keep two rows with a suffixed id.
    #[test]
    fn kind_conflict_splits_into_two_rows() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(
            &claude,
            r#"{"mcpServers":{"dual":{"command":"node","args":["s.js"]}}}"#,
        )
        .unwrap();

        let pi_dir = home.join(".pi").join("agent");
        std::fs::create_dir_all(&pi_dir).unwrap();
        std::fs::write(
            pi_dir.join("mcp.json"),
            r#"{"mcpServers":{"dual":{"type":"http","url":"https://x.test/mcp"}}}"#,
        )
        .unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        import_all(&conn).unwrap();
        let rows = list(&conn).unwrap();
        assert_eq!(rows.len(), 2, "stdio+http conflict should keep 2 rows");
        assert!(rows.iter().any(|r| r.id == "dual"), "canonical stdio row");
        assert!(
            rows.iter().any(|r| r.id == "dual-pi-cli"),
            "suffixed http row, got ids: {:?}",
            rows.iter().map(|r| &r.id).collect::<Vec<_>>()
        );
    }

    /// import_scan aggregates a cross-CLI server into one candidate.
    #[test]
    fn import_scan_aggregates_cross_cli() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(
            &claude,
            r#"{"mcpServers":{"shared":{"command":"npx","args":["x"]}}}"#,
        )
        .unwrap();
        let pi_dir = home.join(".pi").join("agent");
        std::fs::create_dir_all(&pi_dir).unwrap();
        std::fs::write(
            pi_dir.join("mcp.json"),
            r#"{"mcpServers":{"shared":{"command":"npx","args":["x"]}}}"#,
        )
        .unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let cands = import_scan(&conn).unwrap();
        assert_eq!(cands.len(), 1, "one aggregated candidate");
        let c = &cands[0];
        assert_eq!(c.name, "shared");
        assert!(c.agent_ids.contains(&"claude-code-cli".to_string()));
        assert!(c.agent_ids.contains(&"pi-cli".to_string()));
        assert!(!c.transports_conflict, "same kind → no conflict");
    }

    /// save() canonicalizes the id from the name, ignoring a dirty caller id.
    #[test]
    fn save_canonicalizes_id_from_name() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);
        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, r#"{"mcpServers":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        // Caller passes an empty id and a mixed-case name with trailing junk.
        let srv = McpServer {
            id: "".into(),
            name: "Foo Bar-".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["x".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        let saved = save(&conn, &srv).unwrap();
        assert_eq!(saved.id, "foo-bar", "id should be slugified from name");
        assert_eq!(saved.name, "Foo Bar-");
    }

    /// Per-CLI env overrides layer on top of the base env when syncing: a CLI
    /// with no override gets the base env; a CLI with an override gets the
    /// union, with the override winning on key clash.
    #[test]
    fn per_cli_env_override_merges_on_sync() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, r#"{"mcpServers":{}}"#).unwrap();
        let pi_dir = home.join(".pi").join("agent");
        std::fs::create_dir_all(&pi_dir).unwrap();
        std::fs::write(pi_dir.join("mcp.json"), r#"{"mcpServers":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        // Base env {A: "1", SHARED: "base"}; pi overrides {SHARED: "pi", B: "2"}.
        let mut base_env = BTreeMap::new();
        base_env.insert("A".into(), "1".into());
        base_env.insert("SHARED".into(), "base".into());
        let mut pi_ov = BTreeMap::new();
        pi_ov.insert("SHARED".into(), "pi".into());
        pi_ov.insert("B".into(), "2".into());
        let mut overrides = BTreeMap::new();
        overrides.insert("pi-cli".into(), pi_ov);

        let srv = McpServer {
            id: "envtest".into(),
            name: "envtest".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["x".into()],
                env: base_env,
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into(), "pi-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: overrides,
        };
        save(&conn, &srv).unwrap();

        // claude (no override): base env only.
        let claude_text = std::fs::read_to_string(&claude).unwrap();
        assert!(claude_text.contains(r#""A": "1""#), "claude gets base A");
        assert!(
            claude_text.contains(r#""SHARED": "base""#),
            "claude gets base SHARED"
        );
        assert!(!claude_text.contains(r#""B""#), "claude has no B");

        // pi (override): union, SHARED overridden, B added.
        let pi_text = std::fs::read_to_string(pi_dir.join("mcp.json")).unwrap();
        assert!(pi_text.contains(r#""A": "1""#), "pi gets base A");
        assert!(
            pi_text.contains(r#""SHARED": "pi""#),
            "pi override wins for SHARED"
        );
        assert!(pi_text.contains(r#""B": "2""#), "pi gets override B");
    }

    /// Renaming a server must drop the old row + its CLI file entries, not
    /// leave an orphan id and a stale `Old Name` key in the providers' files.
    #[test]
    fn rename_drops_old_row_and_cli_entries() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, r#"{"mcpServers":{}}"#).unwrap();
        let oc_dir = home.join(".config").join("opencode");
        std::fs::create_dir_all(&oc_dir).unwrap();
        std::fs::write(oc_dir.join("opencode.json"), r#"{"mcp":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "old-name".into(),
            name: "Old Name".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["x".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into(), "opencode-desktop".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        let saved = save(&conn, &srv).unwrap();
        assert_eq!(saved.id, "old-name");
        assert!(crate::db::get_mcp_server(&conn, "old-name").unwrap().is_some());

        // Rename → new id.
        let renamed = McpServer {
            id: "old-name".into(),
            name: "New Name".into(),
            ..srv
        };
        let saved2 = save(&conn, &renamed).unwrap();
        assert_eq!(saved2.id, "new-name");
        assert!(
            crate::db::get_mcp_server(&conn, "old-name").unwrap().is_none(),
            "old row must be deleted on rename"
        );
        assert!(crate::db::get_mcp_server(&conn, "new-name").unwrap().is_some());

        // Both CLI files now reference the new name only.
        let claude_text = std::fs::read_to_string(&claude).unwrap();
        assert!(
            !claude_text.contains("Old Name"),
            "claude file dropped old name: {claude_text}"
        );
        assert!(claude_text.contains("New Name"));
        let oc_text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(
            !oc_text.contains("Old Name"),
            "opencode file dropped old name: {oc_text}"
        );
        assert!(oc_text.contains("New Name"));
    }

    /// Editing a server's transport/env WITHOUT renaming must NOT delete the
    /// row. Only true renames (canonical id shifts) trigger cleanup.
    #[test]
    fn edit_transport_does_not_delete_row() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, r#"{"mcpServers":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "stable".into(),
            name: "stable".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["v1".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();
        let edited = McpServer {
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["v2".into()],
                env: BTreeMap::new(),
                url: None,
            },
            ..srv
        };
        let saved = save(&conn, &edited).unwrap();
        assert_eq!(saved.id, "stable");
        assert!(crate::db::get_mcp_server(&conn, "stable").unwrap().is_some());
    }

    /// Toggling a CLI on when its config file is missing must create the file
    /// (empty object) and write the entry — otherwise the UI shows enabled
    /// chips that disagree with reality.
    #[test]
    fn sync_creates_missing_config_file() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        // Deliberately do NOT create ~/.claude.json — sync must create it.
        let claude = home.join(".claude.json");
        assert!(!claude.exists());

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "fresh".into(),
            name: "fresh".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["x".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();

        let written = std::fs::read_to_string(&claude).unwrap();
        assert!(
            written.contains("\"fresh\""),
            "missing config file must be created with the entry, got: {written}"
        );
    }

    /// The tri-state cycle on opencode: a server can be written with the
    /// native enabled flag off (`disabled`), flipped to on, and dropped
    /// entirely (`absent`) — and the two agent lists stay disjoint throughout.
    #[test]
    fn set_state_cycles_tri_states_on_opencode() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let oc_dir = home.join(".config").join("opencode");
        std::fs::create_dir_all(&oc_dir).unwrap();
        std::fs::write(oc_dir.join("opencode.json"), r#"{"mcp":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "playwright".into(),
            name: "playwright".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["@playwright/mcp@latest".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["opencode-desktop".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();

        // Disabled → entry stays written with the flag off.
        let s =
            set_state(&conn, "playwright", "opencode-desktop", AgentMcpState::Disabled).unwrap();
        assert!(s.enabled_agents.is_empty());
        assert_eq!(s.disabled_agents, vec!["opencode-desktop"]);
        let text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(text.contains(r#""enabled": false"#), "disabled entry, got: {text}");

        // Enabled → flag back on, disabled list cleared (invariant).
        let s =
            set_state(&conn, "playwright", "opencode-desktop", AgentMcpState::Enabled).unwrap();
        assert_eq!(s.enabled_agents, vec!["opencode-desktop"]);
        assert!(s.disabled_agents.is_empty());
        let text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(text.contains(r#""enabled": true"#), "enabled entry, got: {text}");

        // Absent → entry removed from the file entirely.
        let s =
            set_state(&conn, "playwright", "opencode-desktop", AgentMcpState::Absent).unwrap();
        assert!(s.enabled_agents.is_empty() && s.disabled_agents.is_empty());
        let text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(!text.contains("playwright"), "entry must be dropped, got: {text}");
    }

    /// A server enabled on claude and written-but-disabled on opencode syncs
    /// the right flag into each file: claude's format has no enabled field
    /// (plain entry), opencode's carries `enabled: false`.
    #[test]
    fn sync_writes_disabled_entry_with_enabled_false() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let claude = home.join(".claude.json");
        std::fs::create_dir_all(claude.parent().unwrap()).unwrap();
        std::fs::write(&claude, r#"{"mcpServers":{}}"#).unwrap();
        let oc_dir = home.join(".config").join("opencode");
        std::fs::create_dir_all(&oc_dir).unwrap();
        std::fs::write(oc_dir.join("opencode.json"), r#"{"mcp":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "playwright".into(),
            name: "playwright".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["@playwright/mcp@latest".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec!["opencode-desktop".into()],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();

        let oc_text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(
            oc_text.contains(r#""enabled": false"#),
            "opencode disabled flag, got: {oc_text}"
        );
        assert!(oc_text.contains("playwright"));

        let claude_text = std::fs::read_to_string(&claude).unwrap();
        assert!(claude_text.contains("playwright"));
        assert!(
            !claude_text.contains("enabled"),
            "claude format has no enabled field: {claude_text}"
        );
    }

    /// Importing an opencode entry with `enabled: false` must preserve the
    /// state: the agent lands in `disabled_agents` and the import sync writes
    /// the flag back as false — importing never force-enables a server the
    /// file says is off.
    #[test]
    fn import_preserves_disabled_flag() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let oc_dir = home.join(".config").join("opencode");
        std::fs::create_dir_all(&oc_dir).unwrap();
        std::fs::write(
            oc_dir.join("opencode.json"),
            r#"{"mcp":{"playwright":{"type":"local","command":["npx","@playwright/mcp@latest"],"enabled":false}}}"#,
        )
        .unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        // Scan surfaces the candidate with the flag.
        let cands = import_scan(&conn).unwrap();
        assert_eq!(cands.len(), 1);
        assert_eq!(cands[0].disabled_in, vec!["opencode-desktop"]);

        let s = import_one(&conn, "opencode-desktop", "playwright").unwrap();
        assert!(
            s.enabled_agents.is_empty(),
            "must not force-enable: {:?}",
            s.enabled_agents
        );
        assert_eq!(s.disabled_agents, vec!["opencode-desktop"]);

        // The entry in the file still says disabled after the import sync.
        let text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(text.contains(r#""enabled": false"#), "flag preserved, got: {text}");
    }

    /// `toggle` off means *absent*: it drops the entry from the file AND
    /// clears any prior written-but-disabled state, keeping the two lists
    /// disjoint.
    #[test]
    fn toggle_absent_clears_disabled_state() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let oc_dir = home.join(".config").join("opencode");
        std::fs::create_dir_all(&oc_dir).unwrap();
        std::fs::write(oc_dir.join("opencode.json"), r#"{"mcp":{}}"#).unwrap();

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "playwright".into(),
            name: "playwright".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["@playwright/mcp@latest".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec![],
            disabled_agents: vec!["opencode-desktop".into()],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();
        assert!(std::fs::read_to_string(oc_dir.join("opencode.json"))
            .unwrap()
            .contains("playwright"));

        let s = toggle(&conn, "playwright", "opencode-desktop", false).unwrap();
        assert!(s.enabled_agents.is_empty());
        assert!(s.disabled_agents.is_empty(), "toggle off must clear disabled state");
        let text = std::fs::read_to_string(oc_dir.join("opencode.json")).unwrap();
        assert!(!text.contains("playwright"), "entry must be dropped, got: {text}");
    }

    /// `unmanage` drops the DB row but LEAVES the entry in agent config files
    /// (it keeps working, becomes Importable) — the inverse of import, and the
    /// key difference from `delete`, which also strips config entries.
    #[test]
    fn unmanage_keeps_agent_config_entries() {
        let _lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let (home, _home_g) = temp_home();
        std::env::set_var("NESTRA_HOME_DIR", &home);

        let conn = Connection::open_in_memory().unwrap();
        crate::db::migrate(&conn).unwrap();

        let srv = McpServer {
            id: "filesystem".into(),
            name: "filesystem".into(),
            transport: McpTransport {
                kind: McpKind::Stdio,
                command: Some("npx".into()),
                args: vec!["-y".into(), "@modelcontextprotocol/server-filesystem".into()],
                env: BTreeMap::new(),
                url: None,
            },
            enabled_agents: vec!["claude-code-cli".into()],
            disabled_agents: vec![],
            managed: true,
            env_overrides: BTreeMap::new(),
        };
        save(&conn, &srv).unwrap();
        let claude = home.join(".claude.json");
        assert!(
            std::fs::read_to_string(&claude)
                .unwrap()
                .contains("filesystem"),
            "entry should be written on save"
        );

        unmanage(&conn, "filesystem").unwrap();

        // DB row is gone.
        assert!(
            crate::db::get_mcp_server(&conn, "filesystem")
                .unwrap()
                .is_none(),
            "unmanage must drop the DB row"
        );
        // …but the agent config entry is left in place (unlike delete).
        let after = std::fs::read_to_string(&claude).unwrap();
        assert!(
            after.contains("filesystem"),
            "unmanage must KEEP the config entry, got: {after}"
        );
    }

    /// Registry-churn guard (the "unknown agent" fix): legacy ids from before
    /// agent renames (e.g. `claude-code` → `claude-code-cli`) must be dropped
    /// at the read boundary, and `sync_all` must persist the pruned set.
    #[test]
    fn row_to_server_prunes_unknown_agent_ids_and_sync_persists() {
        // sync_all touches agent config files under the (overridden) home —
        // serialized through the crate-wide HOME_LOCK like the skills tests.
        let _home_lock = crate::HOME_LOCK.lock().unwrap_or_else(|p| p.into_inner());
        let home = tempfile::Builder::new().prefix("").tempdir().unwrap();
        // SAFETY: confined to this serialized test (HOME_LOCK held).
        std::env::set_var("NESTRA_HOME_DIR", home.path());

        let conn = Connection::open_in_memory().unwrap();
        crate::schema::build_v1(&conn).unwrap();
        conn.execute(
            "INSERT INTO mcp_server (id, name, transport_json, enabled_agents,
                                     disabled_agents, created_at)
             VALUES ('s1','codegraph','{}',?1,'[]',0)",
            rusqlite::params![
                serde_json::to_string(&vec!["claude-code".to_string(), "pi".to_string(),
                                            "claude-code-cli".to_string()])
                    .unwrap()
            ],
        )
        .unwrap();

        // Read boundary: legacy ids never surface.
        let row = crate::db::get_mcp_server(&conn, "s1").unwrap().unwrap();
        let server = row_to_server(&conn, row).unwrap();
        assert_eq!(server.enabled_agents, vec!["claude-code-cli".to_string()]);

        // sync_all persists the pruned set (the DB heals on the next sync).
        sync_all(&conn).unwrap();
        let row = crate::db::get_mcp_server(&conn, "s1").unwrap().unwrap();
        assert_eq!(row.enabled_agents, vec!["claude-code-cli".to_string()]);
    }
}
